import { Tokens } from "./tokens";

export const tokenDecimals: { [key in Tokens]: number } = {
  [Tokens.Moon]: 18,
  [Tokens.USDCE]: 6,
  [Tokens.WETH]: 18,
  [Tokens.SNX]: 18,
  [Tokens.GUARD]: 18,
  [Tokens.ETH]: 18,
  [Tokens.EIGEN]: 18,
  [Tokens.ENA]: 18,
  [Tokens.USDe]: 18,
  [Tokens.eETH]: 18,
  [Tokens.sUSDe]: 18,
  [Tokens.wUSDM]: 18,
  [Tokens.ETHFI]: 18,
  [Tokens.SolvBTC]: 18,
  [Tokens.KINTO]: 18,
  [Tokens.MKR]: 18,
  [Tokens.PAXG]: 18,
  [Tokens.XAUT]: 6,
  [Tokens.eUSD]: 18,
  [Tokens.rsENA]: 18,
  [Tokens.rsUSDe]: 18,
  [Tokens.stUSD]: 18,
  [Tokens.stEUR]: 18,
  [Tokens.SOL]: 9,
  [Tokens.SPX]: 8,
  [Tokens.AAVE] : 18,
  [Tokens.aAAVE] : 18,
  [Tokens.aETH] : 18,
  [Tokens.WBTC]: 8,
  [Tokens.aWBTC] : 8,
  [Tokens.weETH]: 18,
  [Tokens.aweETH] : 18,
  [Tokens.USDC]: 6,
  [Tokens.aUSDC] : 6,
  [Tokens.USDT]: 6,
  [Tokens.aUSDT] : 6,
  [Tokens.ARB] : 18,
  [Tokens.aARB] : 18,
  [Tokens.DAI]: 18,
  [Tokens.sDAI]: 18,
  [Tokens.aDAI] : 18,
  [Tokens.LINK] : 18,
  [Tokens.aLINK] : 18,
  [Tokens.GHO] : 18,
  [Tokens.aGHO] : 18,
  [Tokens.rETH] : 18,
  [Tokens.arETH] : 18,
  [Tokens.cbETH] : 18,
  [Tokens.acbETH] : 18,
  [Tokens.cbBTC] : 8,
  [Tokens.acbBTC] : 8,
  [Tokens.WSTETH]: 18,
  [Tokens.aWSTETH]: 18
};
