import { Tokens } from "./tokens";

export const tokenName: { [key in Tokens]: string } = {
  [Tokens.Moon]: "Moon",
  [Tokens.USDCE]: "Bridged USD coin",
  [Tokens.SNX]: "Synthetix Network Token",
  [Tokens.GUARD]: "Guardian",
  [Tokens.ETH]: "Ether",
  [Tokens.EIGEN]: "Eigen",
  [Tokens.ENA]: "ENA",
  [Tokens.USDe]: "USDe",
  [Tokens.eETH]: "ether.fi ETH",
  [Tokens.sUSDe]: "Staked USDe",
  [Tokens.wUSDM]: "Wrapped Mountain Protocol USD",
  [Tokens.ETHFI]: "ether.fi governance token",
  [Tokens.SolvBTC]: "ether.fi governance token",
  [Tokens.MKR]: "Maker",
  [Tokens.PAXG]: "Paxos Gold",
  [Tokens.XAUT]: "Tether Gold",
  [Tokens.eUSD]: "ether.fi USD",
  [Tokens.rsENA]: "Pendle rsENA",
  [Tokens.rsUSDe]: "Pendle rsUSDe",
  [Tokens.stUSD]: "Staked USDA",
  [Tokens.stEUR]: "Staked EURA",
  [Tokens.SOL]: "Wrapped SOL",
  [Tokens.SPX]: "SPX6900",
  [Tokens.sDAI]: "Savings Dai",
  [Tokens.AAVE]: "Aave Token",
  [Tokens.WETH]: "Wrapped Ether",
  [Tokens.WBTC]: "Wrapped Bitcoin",
  [Tokens.weETH]: "Wrapped eETH",
  [Tokens.USDC]: "USD coin",
  [Tokens.USDT]: "Tether USD",
  [Tokens.ARB]: "Arbitrum",
  [Tokens.DAI]: "Dai Stablecoin",
  [Tokens.LINK]: "ChainLink Token",
  [Tokens.GHO]: "Gho Token",
  [Tokens.rETH]: "Rocket Pool ETH",
  [Tokens.cbETH]: "Coinbase Wrapped Staked ETH",
  [Tokens.cbBTC]: "Coinbase Wrapped BTC",
  [Tokens.WSTETH]: "Wrapped liquid staked Ether 2.0",
  [Tokens.USUAL]: "USUAL",
  [Tokens.LDO]: "Lido DAO Token",
  [Tokens.VIRTUAL]: "Virtual Protocol",
  [Tokens.ONDO]: "Ondo",
  [Tokens.PENDLE]: "Pendle",
  [Tokens.CRV]: "Curve DAO Token"
};
