import { Tokens } from "./tokens";

export const tokenSymbol: { [key in Tokens]: string } = {
  [Tokens.Moon]: "MOON",
  [Tokens.USDCE]: "USDC.e",
  [Tokens.SNX]: "SNX",
  [Tokens.GUARD]: "GUARD",
  [Tokens.ETH]: "ETH",
  [Tokens.EIGEN]: "EIGEN",
  [Tokens.ENA]: "ENA",
  [Tokens.USDe]: "USDe",
  [Tokens.eETH]: "eETH",
  [Tokens.sDAI]: "sDAI",
  [Tokens.sUSDe]: "sUSDe",
  [Tokens.wUSDM]: "wUSDM",
  [Tokens.ETHFI]: "ETHFI",
  [Tokens.SolvBTC]: "SolvBTC",
  [Tokens.KINTO]: "KINTO",
  [Tokens.MKR]: "MKR",
  [Tokens.PAXG]: "PAXG",
  [Tokens.XAUT]: "XAUT",
  [Tokens.eUSD]: "eUSD",
  [Tokens.rsENA]: "rsENA",
  [Tokens.rsUSDe]: "rsUSDe",
  [Tokens.stUSD]: "stUSD",
  [Tokens.stEUR]: "stEUR",
  [Tokens.SOL]: "SOL",
  [Tokens.SPX]: "SPX",
  [Tokens.AAVE] : 'AAVE',
  [Tokens.aEthAAVE]: "aEthAAVE",
  [Tokens.aArbAAVE]: "aArbAAVE",
  [Tokens.aBasAAVE]: "aBasAAVE",
  [Tokens.WETH]: "WETH",
  [Tokens.aEthWETH]: "aEthWETH",
  [Tokens.aArbWETH]: "aArbWETH",
  [Tokens.aBasWETH]: "aBasWETH",
  [Tokens.WBTC]: "WBTC",
  [Tokens.aEthWBTC]: "aEthWBTC",
  [Tokens.aArbWBTC]: "aArbWBTC",
  [Tokens.aBasWBTC]: "aBasWBTC",
  [Tokens.weETH]: "weETH",
  [Tokens.aEthweETH]: "aEthweETH",
  [Tokens.aArbweETH]: "aArbweETH",
  [Tokens.aBasweETH]: "aBasweETH",
  [Tokens.USDC]: "USDC",
  [Tokens.aEthUSDC]: "aEthUSDC",
  [Tokens.aArbUSDC]: "aArbUSDC",
  [Tokens.aBasUSDC]: "aBasUSDC",
  [Tokens.USDT]: "USDT",
  [Tokens.aEthUSDT]: "aEthUSDT",
  [Tokens.aArbUSDT]: "aArbUSDT",
  [Tokens.aBasUSDT]: "aBasUSDT",
  [Tokens.ARB] : 'ARB',
  [Tokens.aEthARB]: "aEthARB",
  [Tokens.aArbARB]: "aArbARB",
  [Tokens.aBasARB]: "aBasARB",
  [Tokens.DAI]: "DAI",
  [Tokens.aEthDAI]: "aEthDAI",
  [Tokens.aArbDAI]: "aArbDAI",
  [Tokens.aBasDAI]: "aBasDAI",
  [Tokens.LINK] : 'LINK',
  [Tokens.aEthLINK]: "aEthLINK",
  [Tokens.aArbLINK]: "aArbLINK",
  [Tokens.aBasLINK]: "aBasLINK",
  [Tokens.GHO] : 'GHO',
  [Tokens.aEthGHO]: "aEthGHO",
  [Tokens.aArbGHO]: "aArbGHO",
  [Tokens.aBasGHO]: "aBasGHO",
  [Tokens.rETH] : 'rETH',
  [Tokens.aEthrETH]: "aEthrETH",
  [Tokens.aArbrETH]: "aArbrETH",
  [Tokens.aBasrETH]: "aBasrETH",
  [Tokens.cbETH] : 'cbETH',
  [Tokens.aEthcbETH]: "aEthcbETH",
  [Tokens.aArbcbETH]: "aArbcbETH",
  [Tokens.aBascbETH]: "aBascbETH",
  [Tokens.cbBTC] : 'cbBTC',
  [Tokens.aEthcbBTC]: "aEthcbBTC",
  [Tokens.aArbcbBTC]: "aArbcbBTC",
  [Tokens.aBascbBTC]: "aBascbBTC",
  [Tokens.WSTETH]: "wstETH",
  [Tokens.aEthwstETH]: "aEthwstETH",
  [Tokens.aArbwstETH]: "aArbwstETH",
  [Tokens.aBaswstETH]: "aBaswstETH"
};
