import { Tokens } from "./tokens";

export const tokenName: { [key in Tokens]: string } = {
  [Tokens.Moon]: "Moon",
  [Tokens.USDCE]: "Bridged USD coin",
  [Tokens.SNX]: "Synthetix Network Token",
  [Tokens.GUARD]: "Guardian",
  [Tokens.ETH]: "Ether",
  [Tokens.EIGEN]: "Eigen",
  [Tokens.ENA]: "ENA",
  [Tokens.USDe]: "USDe",
  [Tokens.eETH]: "ether.fi ETH",
  [Tokens.sUSDe]: "Staked USDe",
  [Tokens.wUSDM]: "Wrapped Mountain Protocol USD",
  [Tokens.ETHFI]: "ether.fi governance token",
  [Tokens.SolvBTC]: "ether.fi governance token",
  [Tokens.KINTO]: "Kinto Token",
  [Tokens.MKR]: "Maker",
  [Tokens.PAXG]: "Paxos Gold",
  [Tokens.XAUT]: "Tether Gold",
  [Tokens.eUSD]: "ether.fi USD",
  [Tokens.rsENA]: "Pendle rsENA",
  [Tokens.rsUSDe]: "Pendle rsUSDe",
  [Tokens.stUSD]: "Staked USDA",
  [Tokens.stEUR]: "Staked EURA",
  [Tokens.SOL]: "Wrapped SOL",
  [Tokens.SPX]: "SPX6900",
  [Tokens.sDAI]: "Savings Dai",
  [Tokens.WETH]: "Wrapped Ether",
  [Tokens.aEthWETH]: "Aave Ethereum WETH",
  [Tokens.aArbWETH]: "Aave Arbitrum WETH",
  [Tokens.aBasWETH]: "Aave Base WETH",
  [Tokens.WBTC]: "Wrapped Bitcoin",
  [Tokens.aEthWBTC]: "Aave Ethereum WBTC",
  [Tokens.aArbWBTC]: "Aave Arbitrum WBTC",
  [Tokens.weETH]: "Wrapped eETH",
  [Tokens.aEthweETH]: "Aave Ethereum thETH",
  [Tokens.aArbweETH]: "Aave Arbitrum rbETH",
  [Tokens.aBasweETH]: "Aave Base asETH",
  [Tokens.USDC]: "USD coin",
  [Tokens.aEthUSDC]: "Aave Ethereum USDC",
  [Tokens.aArbUSDC]: "Aave Arbitrum USDC",
  [Tokens.aBasUSDC]: "Aave Base USDC",
  [Tokens.USDT]: "Tether USD",
  [Tokens.aEthUSDT]: "Aave Ethereum USDT",
  [Tokens.aArbUSDT]: "Aave Arbitrum USDT",
  [Tokens.ARB]: "Arbitrum",
  [Tokens.aArbARB]: "Aave Arbitrum ARB",
  [Tokens.DAI]: "Dai Stablecoin",
  [Tokens.aEthDAI]: "Aave Ethereum DAI",
  [Tokens.aArbDAI]: "Aave Arbitrum DAI",
  [Tokens.LINK]: "ChainLink Token",
  [Tokens.aEthLINK]: "Aave Ethereum LINK",
  [Tokens.aArbLINK]: "Aave Arbitrum LINK",
  [Tokens.GHO]: "Gho Token",
  [Tokens.aEthGHO]: "Aave Ethereum GHO",
  [Tokens.aArbGHO]: "Aave Arbitrum GHO",
  [Tokens.rETH]: "Rocket Pool ETH",
  [Tokens.aEthrETH]: "Aave Ethereum rETH",
  [Tokens.aArbrETH]: "Aave Arbitrum rETH",
  [Tokens.cbETH]: "Coinbase Wrapped Staked ETH",
  [Tokens.aEthcbETH]: "Aave Ethereum cbETH",
  [Tokens.aBascbETH]: "Aave Base cbETH",
  [Tokens.cbBTC]: "Coinbase Wrapped BTC",
  [Tokens.aEthcbBTC]: "Aave Ethereum thBTC",
  [Tokens.aBascbBTC]: "Aave Base asBTC",
  [Tokens.AAVE]: "Aave Token",
  [Tokens.aEthAAVE]: "Aave Ethereum AAVE",
  [Tokens.aArbAAVE]: "Aave Arbitrum AAVE",
  [Tokens.WSTETH]: "Wrapped liquid staked Ether 2.0",
  [Tokens.aEthwstETH]: "Aave Ethereum EthETH",
  [Tokens.aArbwstETH]: "Aave Arbitrum ArbETH",
  [Tokens.aBaswstETH]: "Aave Base BasETH",
};
