import { Tokens } from "./tokens";

export const tokenDecimals: { [key in Tokens]: number } = {
  [Tokens.Moon]: 18,
  [Tokens.USDCE]: 6,
  [Tokens.SNX]: 18,
  [Tokens.GUARD]: 18,
  [Tokens.ETH]: 18,
  [Tokens.EIGEN]: 18,
  [Tokens.ENA]: 18,
  [Tokens.USDe]: 18,
  [Tokens.eETH]: 18,
  [Tokens.sUSDe]: 18,
  [Tokens.wUSDM]: 18,
  [Tokens.ETHFI]: 18,
  [Tokens.SolvBTC]: 18,
  [Tokens.KINTO]: 18,
  [Tokens.MKR]: 18,
  [Tokens.PAXG]: 18,
  [Tokens.XAUT]: 6,
  [Tokens.eUSD]: 18,
  [Tokens.rsENA]: 18,
  [Tokens.rsUSDe]: 18,
  [Tokens.stUSD]: 18,
  [Tokens.stEUR]: 18,
  [Tokens.SOL]: 9,
  [Tokens.SPX]: 8,
  [Tokens.AAVE] : 18,
  [Tokens.aEthAAVE]: 18,
  [Tokens.aArbAAVE]: 18,
  [Tokens.aBasAAVE]: 18,
  [Tokens.WETH]: 18,
  [Tokens.aEthWETH]: 18,
  [Tokens.aArbWETH]: 18,
  [Tokens.aBasWETH]: 18,
  [Tokens.WBTC]: 8,
  [Tokens.aEthWBTC]: 8,
  [Tokens.aArbWBTC]: 8,
  [Tokens.aBasWBTC]: 8,
  [Tokens.weETH]: 18,
  [Tokens.aEthweETH]: 18,
  [Tokens.aArbweETH]: 18,
  [Tokens.aBasweETH]: 18,
  [Tokens.USDC]: 6,
  [Tokens.aEthUSDC]: 6,
  [Tokens.aArbUSDC]: 6,
  [Tokens.aBasUSDC]: 6,
  [Tokens.USDT]: 6,
  [Tokens.aEthUSDT]: 6,
  [Tokens.aArbUSDT]: 6,
  [Tokens.aBasUSDT]: 6,
  [Tokens.ARB] : 18,
  [Tokens.aEthARB]: 18,
  [Tokens.aArbARB]: 18,
  [Tokens.aBasARB]: 18,
  [Tokens.DAI]: 18,
  [Tokens.sDAI]: 18,
  [Tokens.aEthDAI]: 18,
  [Tokens.aArbDAI]: 18,
  [Tokens.aBasDAI]: 18,
  [Tokens.LINK] : 18,
  [Tokens.aEthLINK]: 18,
  [Tokens.aArbLINK]: 18,
  [Tokens.aBasLINK]: 18,
  [Tokens.GHO] : 18,
  [Tokens.aEthGHO]: 18,
  [Tokens.aArbGHO]: 18,
  [Tokens.aBasGHO]: 18,
  [Tokens.rETH] : 18,
  [Tokens.aEthrETH]: 18,
  [Tokens.aArbrETH]: 18,
  [Tokens.aBasrETH]: 18,
  [Tokens.cbETH] : 18,
  [Tokens.aEthcbETH]: 18,
  [Tokens.aArbcbETH]: 18,
  [Tokens.aBascbETH]: 18,
  [Tokens.cbBTC] : 8,
  [Tokens.aEthcbBTC]: 8,
  [Tokens.aArbcbBTC]: 8,
  [Tokens.aBascbBTC]: 8,
  [Tokens.WSTETH]: 18,
  [Tokens.aEthwstETH]: 18,
  [Tokens.aArbwstETH]: 18,
  [Tokens.aBaswstETH]: 18
};
