import { Tokens } from "./tokens";

export const tokenSymbol: { [key in Tokens]: string } = {
  [Tokens.Moon]: "MOON",
  [Tokens.USDCE]: "USDC.e",
  [Tokens.USDC]: "USDC",
  [Tokens.WETH]: "WETH",
  [Tokens.SNX]: "SNX",
  [Tokens.WSTETH]: "wstETH",
  [Tokens.DAI]: "DAI",
  [Tokens.GUARD]: "GUARD",
  [Tokens.ETH]: "ETH",
  [Tokens.EIGEN]: "EIGEN",
  [Tokens.ENA]: "ENA",
  [Tokens.USDe]: "USDe",
  [Tokens.eETH]: "eETH",
  [Tokens.sDAI]: "sDAI",
  [Tokens.sUSDe]: "sUSDe",
  [Tokens.wUSDM]: "wUSDM",
  [Tokens.weETH]: "weETH",
  [Tokens.ETHFI]: "ETHFI",
  [Tokens.SolvBTC]: "SolvBTC",
  [Tokens.KINTO]: "KINTO",
  [Tokens.MKR]: "MKR",
  [Tokens.PAXG]: "PAXG",
  [Tokens.XAUT]: "XAUT",
  [Tokens.eUSD]: "eUSD",
  [Tokens.rsENA]: "rsENA",
  [Tokens.rsUSDe]: "rsUSDe",
  [Tokens.stUSD]: "stUSD",
  [Tokens.stEUR]: "stEUR",
  [Tokens.SOL]: "SOL",
  [Tokens.SPX]: "SPX",
  [Tokens.AAVE] : 'AAVE',
  [Tokens.aAAVE] : 'aAAVE',
  [Tokens.aETH] : 'aETH',
  [Tokens.WBTC]: "WBTC",
  [Tokens.aWBTC] : 'aWBTC',
  [Tokens.aweETH] : 'aweETH',
  [Tokens.aUSDC] : 'aUSDC',
  [Tokens.USDT]: "USDT",
  [Tokens.aUSDT] : 'aUSDT',
  [Tokens.ARB] : 'ARB',
  [Tokens.aARB] : 'aARB',
  [Tokens.aDAI] : 'aDAI',
  [Tokens.LINK] : 'LINK',
  [Tokens.aLINK] : 'aLINK',
  [Tokens.GHO] : 'GHO',
  [Tokens.aGHO] : 'aGHO',
  [Tokens.rETH] : 'rETH',
  [Tokens.arETH] : 'arETH',
  [Tokens.cbETH] : 'cbETH',
  [Tokens.acbETH] : 'acbETH',
  [Tokens.cbBTC] : 'cbBTC',
  [Tokens.acbBTC] : 'acbBTC'
};
